### ISSUE TITLE
How do I render the button?

### ISSUE THREAD

**Issue by liambrozik** [AlaskaAirlines/OrionStatelessComponents__ods-button#53]
**Is your feature request related to a problem? Please describe.**
The documentation for the button is a bit difficult to parse, with all of this deprecated content and different dependencies and doc files. I  have followed what appear to be steps to render the button (I think?), I have referenced other repos/sample repos (and things have changed?), and I still can't seem to get the button to render in React.

**Describe the solution you'd like**
I think this repo would benefit massively from a **Getting Started** or **How To Render The Button** section. I have worked with ODS before, and it seems to have changed since I last used it, so I think a single section for how to render the button with the latest version would be awesome if kept up to date.

**Comment by blackfalcon** [comment]
When you are saying that you can't get the button to render, what is missing? 

Is the web component not rendering the shadow DOM or is there an issue that the CSS is not being applied to the custom element?

**Comment by blackfalcon** [comment]
Also, I think what you are looking for is in this React demo repo
https://github.com/AlaskaAirlines/OrionReactDemo/blob/master/PROJECT_SETUP.md

**Comment by liambrozik** [comment]
Great question, sorry I should have clarified.

**What I have done:**
Imported the necessary sass file in my sass
`@import "~@alaskaairux/orion-design-tokens/dist/tokens/SCSSVariables";`
And verified that I can use the variables and they display properly.

Imported the auro button in my `App.js`
`import '@alaskaairux/ods-button/dist/auro-button';`

Added the element to my `render()` function
`<auro-button>Hello World</auro-button>`

**What I'm seeing:**
I am simply seeing the text "Hello World" displayed in bold with no other styling. It seems like I may be missing style sheets. I have tried importing the tokens in `App.js` but nothing seemed to work. In the inspector I see `#shadow-root (open)` inside the `<auro-button>` component

**Comment by blackfalcon** [comment]
Sure, I see where the issue is. 

`SCSSVariables` are Auro Sass variables, e.g. `$thing`. The native web components need the Auro CSS Custom Properties in order to render properly.

 Importing `/SCSSVariables` into your primary Sass aggregator will provide access to all the use cases of using Sass variables in your code, e.g. 

```scss
.foo {
  color: $auro-color-background-darker
}
```

When using a web component, the CSS in the component itself is looking for CSS custom properties in the global scope, e.g.

```css
:root {
  --auro-color-background-darker: #01426a
}
```

In order to do this, in your global Sass you could import `SassCustomProperties`. Or you can also import the CSS file `CSSTokenProperties.css` into your App.js file.

Either way, you only need to make this reference once and be sure it is in a global space so that all other UIs will be able to consume this resource. 

Here is the full list of all the pre-processed resources from Tokens
https://github.com/AlaskaAirlines/OrionDesignTokens#install-pre-processed-resources

**Comment by liambrozik** [comment]
Thanks so much, I think this was the missing piece. I had tried importing the `CSSTokenProperties.css` in my App.js but it wasn't working, but after adding `SassCustomProperties` to my global sass file, I am now seeing the correct render and styling of the button.
_Woohoo!_
